import { GoogleGenerativeAI } from "@google/generative-ai";
import { config } from "../config";
import { logger } from "./logger";

export interface LlmMessage {
  role: "system" | "user" | "assistant";
  content: string;
}

export interface LlmOptions {
  temperature?: number;
  maxTokens?: number;
  topP?: number;
  responseJson?: boolean;
}

export interface LlmResult {
  text: string;
  provider: string;
}

/**
 * Wrap a promise so it rejects after `ms` with a clear timeout message.
 * This works for any async operation, including SDKs that do not accept AbortController.
 */
function withTimeout<T>(promise: Promise<T>, ms: number, label: string): Promise<T> {
  return Promise.race([
    promise,
    new Promise<T>((_, reject) =>
      setTimeout(
        () => reject(new Error(`${label} timed out after ${ms}ms`)),
        ms,
      ),
    ),
  ]);
}

/**
 * Unified LLM client. Provider priority:
 * 1. Google Gemini (primary) — gemini-2.5-flash
 * 2. Perplexity (fallback) — Sonar model
 * 3. Hugging Face Inference API (free-tier fallback) — Qwen / Mistral / Llama
 */
export class LlmClient {
  private geminiClient: GoogleGenerativeAI | null = null;
  private initialized = false;

  private getGemini(): GoogleGenerativeAI {
    if (!this.geminiClient) {
      if (!config.gemini.apiKey) {
        throw new Error("GEMINI_API_KEY is not configured");
      }
      this.geminiClient = new GoogleGenerativeAI(config.gemini.apiKey);
    }
    return this.geminiClient;
  }

  isGeminiAvailable(): boolean {
    return Boolean(config.gemini.apiKey);
  }

  isPerplexityAvailable(): boolean {
    return Boolean(config.perplexity.apiKey);
  }

  isHuggingFaceAvailable(): boolean {
    return Boolean(config.huggingface.token);
  }

  private logStatus(): void {
    if (this.initialized) return;
    this.initialized = true;

    const providers: string[] = [];
    if (this.isGeminiAvailable()) providers.push("Gemini (primary)");
    if (this.isPerplexityAvailable()) providers.push("Perplexity (fallback)");
    if (this.isHuggingFaceAvailable()) providers.push("Hugging Face (free fallback)");

    if (providers.length === 0) {
      logger.warn(
        "[LlmClient] No LLM provider configured! Set GEMINI_API_KEY, PERPLEXITY_API_KEY, or HF_TOKEN in .env",
      );
    } else {
      logger.info(`[LlmClient] Providers: ${providers.join(" -> ")}`);
      logger.info(
        `[LlmClient] Request timeout: ${config.ai.requestTimeoutMs}ms`,
      );
    }
  }

  /**
   * Send a chat completion request.
   * Tries Gemini -> Perplexity -> Hugging Face, each with a strict timeout.
   * Returns the generated text and the provider that succeeded.
   */
  async chatCompletion(
    messages: LlmMessage[],
    options: LlmOptions = {},
  ): Promise<LlmResult> {
    this.logStatus();

    const providers: Array<{
      name: string;
      available: boolean;
      call: () => Promise<string>;
    }> = [
      {
        name: "Gemini",
        available: this.isGeminiAvailable(),
        call: () => this.callGemini(messages, options),
      },
      {
        name: "Perplexity",
        available: this.isPerplexityAvailable(),
        call: () => this.callPerplexity(messages, options),
      },
      {
        name: "Hugging Face",
        available: this.isHuggingFaceAvailable(),
        call: () => this.callHuggingFace(messages, options),
      },
    ];

    const timeoutMs = config.ai.requestTimeoutMs;
    const errors: string[] = [];

    for (const provider of providers) {
      if (!provider.available) continue;

      try {
        const text = await withTimeout(
          provider.call(),
          timeoutMs,
          provider.name,
        );
        if (!text || !text.trim()) {
          throw new Error(`${provider.name} returned empty content`);
        }
        logger.info(`[LlmClient] Response generated by ${provider.name}`);
        return { text, provider: provider.name };
      } catch (err: any) {
        const message = err.message || String(err);
        logger.warn(`[LlmClient] ${provider.name} failed: ${message}`);
        errors.push(`${provider.name}: ${message}`);
      }
    }

    throw new Error(
      `All LLM providers failed. ${errors.join(" | ")}`,
    );
  }

  // ========================================
  // GEMINI
  // ========================================

  private async callGemini(
    messages: LlmMessage[],
    options: LlmOptions,
  ): Promise<string> {
    const client = this.getGemini();
    const model = client.getGenerativeModel({ model: config.gemini.model });

    const contents: Array<{ role: string; parts: Array<{ text: string }> }> = [];

    for (const msg of messages) {
      // Gemini only supports "user" and "model" roles
      let role: string;
      if (msg.role === "assistant") role = "model";
      else if (msg.role === "system") role = "user";
      else role = "user";
      contents.push({ role, parts: [{ text: msg.content }] });
    }

    const generationConfig: any = {
      temperature: options.temperature ?? 0.3,
      maxOutputTokens: options.maxTokens ?? 2048,
    };

    if (options.topP !== undefined) {
      generationConfig.topP = options.topP;
    }

    if (options.responseJson) {
      generationConfig.responseMimeType = "application/json";
    }

    const result = await model.generateContent({
      contents,
      generationConfig,
    });

    return result.response.text();
  }

  // ========================================
  // PERPLEXITY (fallback)
  // ========================================

  private async callPerplexity(
    messages: LlmMessage[],
    options: LlmOptions,
  ): Promise<string> {
    // Perplexity Sonar API rejects "system" role - merge into first user message
    const adapted = this.adaptForPerplexity(messages);

    const body: Record<string, unknown> = {
      model: config.perplexity.model,
      messages: adapted,
      temperature: options.temperature ?? 0.3,
      max_tokens: options.maxTokens ?? 2048,
    };

    if (options.topP !== undefined) {
      body.top_p = options.topP;
    }

    const response = await fetch("https://api.perplexity.ai/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${config.perplexity.apiKey}`,
      },
      body: JSON.stringify(body),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(
        `Perplexity HTTP ${response.status}: ${errorText.slice(0, 400)}`,
      );
    }

    const data = (await response.json()) as any;
    const content = data?.choices?.[0]?.message?.content;
    if (!content) {
      throw new Error("Perplexity returned empty content");
    }

    return content;
  }

  // ========================================
  // HUGGING FACE (free-tier fallback)
  // ========================================

  private async callHuggingFace(
    messages: LlmMessage[],
    options: LlmOptions,
  ): Promise<string> {
    // Merge system prompts into the first user message for instruction models
    const adapted = this.adaptForHuggingFace(messages);

    const response = await fetch(
      `https://api-inference.huggingface.co/models/${config.huggingface.model}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${config.huggingface.token}`,
        },
        body: JSON.stringify({
          inputs: adapted,
          parameters: {
            temperature: options.temperature ?? 0.3,
            max_new_tokens: options.maxTokens ?? 2048,
            return_full_text: false,
          },
        }),
      },
    );

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(
        `Hugging Face HTTP ${response.status}: ${errorText.slice(0, 400)}`,
      );
    }

    const data = (await response.json()) as any;

    // Hugging Face text-generation returns an array of { generated_text: string }
    if (Array.isArray(data) && data[0]?.generated_text) {
      return data[0].generated_text;
    }

    // Some endpoints return { generated_text: string }
    if (data?.generated_text) {
      return data.generated_text;
    }

    // Conversational / chat-completion endpoints return { choices: [...] }
    const content = data?.choices?.[0]?.message?.content;
    if (content) {
      return content;
    }

    throw new Error("Hugging Face returned unexpected response shape");
  }

  private adaptForPerplexity(
    messages: LlmMessage[],
  ): Array<{ role: "user" | "assistant"; content: string }> {
    const systemParts: string[] = [];
    const result: Array<{ role: "user" | "assistant"; content: string }> = [];
    let merged = false;

    for (const msg of messages) {
      if (msg.role === "system") {
        systemParts.push(msg.content);
      } else {
        const role = msg.role === "user" ? "user" : "assistant";
        if (!merged && systemParts.length && role === "user") {
          result.push({
            role: "user",
            content: systemParts.join("\n\n") + "\n\n" + msg.content,
          });
          merged = true;
        } else {
          result.push({ role, content: msg.content });
        }
      }
    }

    if (!merged && systemParts.length) {
      result.unshift({ role: "user", content: systemParts.join("\n\n") });
    }

    return result;
  }

  private adaptForHuggingFace(messages: LlmMessage[]): string {
    // Build a simple prompt string from messages.
    // This works well for instruction-tuned models like Qwen, Mistral, and Llama.
    const parts: string[] = [];
    let systemPrompt = "";

    for (const msg of messages) {
      if (msg.role === "system") {
        systemPrompt = msg.content;
      } else if (msg.role === "user") {
        parts.push(`User: ${msg.content}`);
      } else {
        parts.push(`Assistant: ${msg.content}`);
      }
    }

    let prompt = "";
    if (systemPrompt) {
      prompt += `System: ${systemPrompt}\n\n`;
    }
    prompt += parts.join("\n");
    prompt += "\nAssistant:";

    return prompt;
  }
}

export const llmClient = new LlmClient();
